--- 
app_configs_001: 
  admin_email: james.luo@yale.edu
  auth_types: CAS
  calendar_feed_hash: 4d817eb8ae284f9cf606e61ae637c95d37837ed1fa12465330583ae09121fb8d
  created_at: 2009-09-08 01:29:06
  footer: ""
  id: "1"
  ldap_base: o=yale.edu
  ldap_email: mail
  ldap_first_name: givenname
  ldap_host_address: directory.yale.edu
  ldap_last_name: sn
  ldap_login: uid
  ldap_port: "389"
  mailer_address: adam.bray@yale.edu
  updated_at: 2011-06-09 16:53:22
  use_ldap: "1"
