--- 
app_configs_001: 
  auth_types: CAS, built-in
  calendar_feed_hash: gd345z68k223h70xkcdgd345z68k223h
  created_at: 2009-07-09 18:39:41
  footer: "Certifying authority: Adam Bray, Asst. Manager, Student Technology<br/>Last modified: Wed Feb 28 00:17:00 EST 2007"
  id: "2"
  ldap_base: ou=People,o=yale.edu
  ldap_email: mail
  ldap_first_name: givenname
  ldap_host_address: directory.yale.edu
  ldap_last_name: sn
  ldap_login: uid
  ldap_port: "389"
  mailer_address: trueesting@contact.ben
  updated_at: 2009-08-04 20:23:27
  use_ldap: true
