--- 
department_configs_001: 
  admin_round_option: 
  auto_remind: "1"
  auto_warn: "1"
  can_take_passed_sub: "1"
  created_at: 2009-09-08 01:29:16
  day: "6"
  department_id: "1"
  description_min: "4"
  early_signin: "60"
  end_of_month: "0"
  grace_period: "7"
  id: "1"
  mailer_address: noreply@shifts.app
  monthly: "0"
  payform_time_limit: 
  printed_message: |-
    This payform has already been printed and may no longer be edited.
    
    If there is a problem that needs to be addressed, please talk to your supervisor.
  reason_min: "4"
  reminder_message: Please remember to submit your payform for this week.
  schedule_end: "1440"
  schedule_start: "540"
  stale_shift: "1"
  stats_mailer_address: adam.bray@yale.edu, laura.tomas@yale.edu
  time_increment: "15"
  unscheduled_shifts: "1"
  updated_at: 2010-10-04 20:19:46
  warning_message: |-
    You have not submitted payforms for the weeks ending on the following dates:
    
    @weeklist@
    
    Please submit your payforms. If some of the weeks listed are weeks during which you did not work, please just submit a blank payform.
  warning_weeks: "2"
  weekend_shifts: "1"
