--- 
user_configs_001: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "1"
  updated_at: 2009-06-22 17:56:18
  user_id: "13"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_002: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "2"
  updated_at: 2009-06-22 17:56:18
  user_id: "14"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_003: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "3"
  updated_at: 2009-08-06 16:56:41
  user_id: "15"
  view_loc_groups: 2, 3
  view_week: ""
  watched_data_objects: ""
user_configs_004: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "4"
  updated_at: 2009-06-22 17:56:18
  user_id: "16"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_005: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "5"
  updated_at: 2009-06-22 17:56:18
  user_id: "17"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_006: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "6"
  updated_at: 2009-06-22 17:56:18
  user_id: "18"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_007: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "7"
  updated_at: 2009-07-11 14:39:06
  user_id: "20"
  view_loc_groups: 2, 3, 4
  view_week: whole_period
  watched_data_objects: ""
user_configs_008: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "8"
  updated_at: 2009-06-22 17:56:18
  user_id: "21"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_009: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "9"
  updated_at: 2009-06-22 17:56:18
  user_id: "22"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_010: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "10"
  updated_at: 2009-06-22 17:56:18
  user_id: "23"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_011: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "11"
  updated_at: 2009-10-19 15:51:49
  user_id: "24"
  view_loc_groups: 2, 3, 4
  view_week: whole_period
  watched_data_objects: ""
user_configs_012: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "12"
  updated_at: 2009-06-22 17:56:18
  user_id: "26"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_013: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "13"
  updated_at: 2009-06-22 17:56:18
  user_id: "27"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_014: 
  created_at: 2009-06-22 17:42:57
  default_dept: "1"
  id: "14"
  updated_at: 2009-06-22 17:56:18
  user_id: "28"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_015: 
  created_at: 2009-06-30 19:58:09
  default_dept: 
  id: "19"
  updated_at: 2009-06-30 19:58:09
  user_id: "49"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_016: 
  created_at: 2009-06-30 19:58:26
  default_dept: 
  id: "20"
  updated_at: 2009-06-30 19:58:26
  user_id: "50"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_017: 
  created_at: 2009-06-30 20:23:05
  default_dept: 
  id: "21"
  updated_at: 2009-06-30 20:23:05
  user_id: "51"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
user_configs_018: 
  created_at: 2009-07-10 12:59:25
  default_dept: 
  id: "23"
  updated_at: 2009-07-10 12:59:25
  user_id: "52"
  view_loc_groups: ""
  view_week: ""
  watched_data_objects: ""
